import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#c41e2a', // CJC Red theme
    paddingTop: 50,
  },
  textWhite: {
    color: '#fff',
    textAlign: 'center',
    marginTop: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  queueBadge: {
    backgroundColor: '#fff', 
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  queueText: {
    color: '#c41e2a',
    fontWeight: 'bold',
    fontSize: 12,
  },
  scannerWrapper: {
    flex: 1,
    backgroundColor: '#000',
    overflow: 'hidden',
    position: 'relative',
  },
  scannerContainer: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reticle: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 20,
  },
  processingText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  resultCardWrapper: {
    flex: 1,
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  resultCard: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  resultIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  bgSuccess: {
    backgroundColor: '#16a34a',
  },
  bgOffline: {
    backgroundColor: '#2563eb',
  },
  bgError: {
    backgroundColor: '#dc2626',
  },
  statusTag: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 20,
    marginBottom: 14,
  },
  tagSuccess: {
    backgroundColor: '#dcfce7',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  tagWarning: {
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  tagOffline: {
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  tagError: {
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  statusTagText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
  },
  textSuccess: {
    color: '#15803d',
  },
  textWarning: {
    color: '#b45309',
  },
  textOffline: {
    color: '#1d4ed8',
  },
  textError: {
    color: '#b91c1c',
  },
  resultTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 8,
    textAlign: 'center',
  },
  resultMessage: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: '500',
    marginBottom: 20,
  },
  resultFooterHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    width: '100%',
    justifyContent: 'center',
  },
  resultFooterHintText: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: '600',
  },
  footer: {
    flexDirection: 'row',
    padding: 20,
    backgroundColor: '#fff',
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
  },
  button: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#c41e2a',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonSecondary: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f9fafb',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  buttonTextSecondary: {
    color: '#4b5563',
    fontWeight: 'bold',
    fontSize: 15,
  },
  modalBg: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 30,
    paddingBottom: Platform.OS === 'ios' ? 50 : 30,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#c41e2a',
    marginBottom: 20,
  },
  input: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    padding: 16,
    fontSize: 18,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginBottom: 20,
  },
  buttonSubmit: {
    backgroundColor: '#c41e2a',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonCancel: {
    backgroundColor: '#f3f4f6',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
  },
  buttonTextCancel: {
    color: '#4b5563',
    fontWeight: 'bold',
    fontSize: 16,
  },
  
  // SPLASH SCREEN STYLES
  splashContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#fcf9f2',
    zIndex: 9999,
    elevation: 9999,
  },
  splashBg: {
    flex: 1,
    justifyContent: 'space-between',
    padding: 20,
    paddingTop: 50,
  },
  splashTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  splashBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  splashBadgeText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#1e293b',
    marginLeft: 4,
    letterSpacing: 1,
  },
  splashBadgeRight: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  splashCjcText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#7f1d1d',
    letterSpacing: 1,
  },
  splashMottoText: {
    fontSize: 7,
    fontWeight: 'bold',
    color: '#d97706',
    letterSpacing: 0.5,
  },
  splashCenterContent: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  emblemContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emblemGlow: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(217, 119, 6, 0.2)',
    transform: [{ scale: 1.2 }],
  },
  emblemOuterRing: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#d97706',
    padding: 6,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  emblemInnerRing: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashMainTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#7f1d1d',
    letterSpacing: 1,
    textAlign: 'center',
  },
  splashDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 200,
    marginVertical: 12,
  },
  splashDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#d97706',
    opacity: 0.5,
  },
  splashDividerDiamond: {
    width: 6,
    height: 6,
    backgroundColor: '#d97706',
    transform: [{ rotate: '45deg' }],
    marginHorizontal: 10,
  },
  splashSubTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#7f1d1d',
    letterSpacing: 2,
    textAlign: 'center',
  },
  splashDescText: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: '600',
    marginTop: 6,
    letterSpacing: 0.5,
  },
  splashBottomSection: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  loadingBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    marginBottom: 8,
  },
  loadingBarTrack: {
    flex: 1,
    height: 10,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    overflow: 'hidden',
    padding: 2,
  },
  loadingBarFill: {
    height: '100%',
    backgroundColor: '#c41e2a',
    borderRadius: 10,
  },
  loadingBarPercent: {
    fontSize: 12,
    fontWeight: '900',
    color: '#7f1d1d',
    marginLeft: 10,
    width: 35,
  },
  loadingStatusText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  }
});

export default styles;
